# Generated by Django 4.2.5 on 2023-09-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captcha',
        ),
    ]
