# Generated by Django 4.2.5 on 2023-09-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_delete_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='captcha',
        ),
    ]
